apiVersion: v1
kind: Service
metadata:
  name: vllm-api-nodeport
  namespace: llm-platform
spec:
  selector:
    app: vllm
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32004