apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: llm-platform
spec:
  selector:
    app: litellm
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 32003