apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: llm-platform
spec:
  type: NodePort
  ports:
    - port: 5678
      targetPort: 5678
      nodePort: 32001
  selector:
    app: n8n